// ui/src/app/components/filters/filters.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-filters',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="bg-white/80 backdrop-blur rounded-xl shadow-sm p-6 md:p-8 m-2">
      <div class="space-y-6">
        <div>
          <div class="flex items-center gap-3 mb-4">
            <span class="material-symbols-outlined text-2xl text-blue-600">category</span>
            <h3 class="text-lg font-semibold">Categories</h3>
          </div>
          <div class="flex flex-wrap gap-2">
            <button
              *ngFor="let category of categories"
              (click)="onToggleCategory.emit(category)"
              [class]="'px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200 ' +
                (selectedCategories.includes(category)
                  ? 'bg-blue-100 text-blue-800 hover:bg-blue-200'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200')"
            >
              {{ category }}
            </button>
          </div>
        </div>

        <div>
          <div class="flex items-center gap-3 mb-4">
            <span class="material-symbols-outlined text-2xl text-blue-600">public</span>
            <h3 class="text-lg font-semibold">Sources</h3>
          </div>
          <div class="flex flex-wrap gap-2">
            <button
              *ngFor="let source of sources"
              (click)="onToggleSource.emit(source)"
              [class]="'px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200 ' +
                (selectedSources.includes(source)
                  ? 'bg-blue-100 text-blue-800 hover:bg-blue-200'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200')"
            >
              {{ source }}
            </button>
          </div>
        </div>
      </div>
    </div>
  `
})
export class FiltersComponent {
  @Input() categories: string[] = [];
  @Input() sources: string[] = [];
  @Input() selectedCategories: string[] = [];
  @Input() selectedSources: string[] = [];
  @Output() onToggleCategory = new EventEmitter<string>();
  @Output() onToggleSource = new EventEmitter<string>();
}

// ui/src/components/Filters.tsx
import { Search, Tag } from 'lucide-react';

interface FiltersProps {
  categories: string[];
  selectedCategory: string;
  searchTerm: string;
  onCategoryChange: (category: string) => void;
  onSearchChange: (search: string) => void;
}

export function Filters({
  categories,
  selectedCategory,
  searchTerm,
  onCategoryChange,
  onSearchChange,
}: FiltersProps) {
  return (
    <div className="w-full space-y-4">
      <div className="relative">
        <div className="absolute inset-y-0 left-3 flex items-center pointer-events-none">
          <Search className="text-gray-400" size={18} />
        </div>
        <input
          type="text"
          value={searchTerm}
          onChange={(e) => onSearchChange(e.target.value)}
          placeholder="Search events..."
          className="w-full pl-10 pr-4 py-2.5 text-sm bg-white border border-gray-200 rounded-lg placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
        />
      </div>
      
      <div>
        <div className="flex items-center gap-2 mb-3 text-sm text-gray-600">
          <Tag size={16} className="text-blue-500" />
          <span className="font-medium">Categories</span>
        </div>
        <div className="flex flex-wrap gap-2">
          <button
            onClick={() => onCategoryChange('')}
            className={`px-3 py-1.5 text-sm font-medium rounded-lg transition-all ${
              selectedCategory === ''
                ? 'bg-blue-600 text-white shadow-sm'
                : 'bg-white text-gray-600 border border-gray-200 hover:bg-gray-50'
            }`}
          >
            All
          </button>
          {categories.map((category) => (
            <button
              key={category}
              onClick={() => onCategoryChange(category)}
              className={`px-3 py-1.5 text-sm font-medium rounded-lg transition-all ${
                selectedCategory === category
                  ? 'bg-blue-600 text-white shadow-sm'
                  : 'bg-white text-gray-600 border border-gray-200 hover:bg-gray-50'
              }`}
            >
              {category}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}
